name: Jenkins Smoketest
on:
  workflow_call:
    inputs:
      ziti-version:
        description: 'Semantic Version from `ziti-ci -q get-current-version`'
        type: string
        required: true    # error if this workflow is called from main.yml and the ziti_version is missing
  workflow_dispatch:
    inputs:
      ziti-version:
        description: 'Semantic Version from `ziti-ci -q get-current-version`'
        type: string
        required: false   # this allows manually triggering the smoketest with the UNKNOWN version default

# cancel older, redundant runs of same workflow on same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  jenkins-smoketest:
    runs-on: ubuntu-latest
    name: Jenkins On-Demand Smoketest
    steps:
      - name: debug ziti-version input
        run: |
          echo ziti-version=${{ inputs.ziti-version || github.event.inputs.ziti-version }} 
      - name: Send Webhook to Jenkinstest
        uses: openziti/ziti-webhook-action@v2
        if: ${{ env.ZITI_JENKINS_WEBHOOK_URL != null }}
        env:
          ZITI_JENKINS_WEBHOOK_URL: ${{ secrets.ZITI_JENKINS_WEBHOOK_URL }}
        with:
          ziti-id: ${{ secrets.ZITI_JENKINS_IDENTITY }}
          webhook-url: ${{ secrets.ZITI_JENKINS_WEBHOOK_URL }}
          webhook-secret: ${{ secrets.ZITI_JENKINS_WEBHOOK_SECRET }}
          data: |
            ziti-version=${{ inputs.ziti-version || github.event.inputs.ziti-version }}
            branch=${{ github.head_ref || github.ref }}
