name: Jenkins Nightly Smoketest
on:
  workflow_dispatch:
  schedule:
    # Runs "at minute 28 past every 0400 GMT from GitHub main branch"
    - cron: '28 4 * * *'

# cancel older, redundant runs of same workflow on same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  jenkins-nightly-smoketest:
    runs-on: ubuntu-latest
    name: POST Webhook to Jenkinstest
    steps:
      - name: Trigger Nightly Smoketest
        uses: openziti/ziti-webhook-action@v2
        if: ${{ env.ZITI_JENKINS_WEBHOOK_URL != null }}
        env:
          ZITI_JENKINS_WEBHOOK_URL: ${{ secrets.ZITI_JENKINS_WEBHOOK_URL }}
        with:
          ziti-id: ${{ secrets.ZITI_JENKINS_IDENTITY }}
          webhook-url: ${{ secrets.ZITI_JENKINS_WEBHOOK_URL }}
          webhook-secret: ${{ secrets.ZITI_JENKINS_WEBHOOK_SECRET }}
          data: |
            ziti-version=gh-nightly-${{ github.run_id }}
            branch=release-next
            nightly=true

          # These were copied from the Jenkins nightly trigger job's cURL query params
          # location=us-east-1    # not a valid build param in Jenkins
          # deploy_branch=master  # master is default in Jenkins
          # destroy_delay=0       # 0 is default in Jenkins