name: Validation (SDK Status)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  sdk-status-validation:
    name: SDK Status Validation
    uses: ./.github/workflows/validation-test.yml
    secrets: inherit
    with:
      test: sdk-status-test