name: Validation (ER/T Terminators)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  ert-terminator-validation:
    name: ER/T Terminator Validation
    uses: ./.github/workflows/validation-test.yml
    secrets: inherit
    with:
      test: ert-hosting-test