name: Validation (Circuits)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  circuit-validation:
    name: Circuit Validation
    uses: ./.github/workflows/validation-test.yml
    secrets: inherit
    with:
      test: circuit-test