name: Validation (Links)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  links-validation:
    name: Links Validation
    uses: ./.github/workflows/validation-test.yml
    secrets: inherit
    with:
      test: links-test
